import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { sanityClient, urlFor } from "../lib/sanity";
import Link from "next/link";

const recipiesQuery = `*[_type == 'racipe']{
  _id,
  name,
  slug,
  mainImage
}`;

export default function Home({ recipes }) {
  console.log(recipes);
  return (
    <div className={styles.container}>
      <Head>
        <title>LOL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>dome</h2>

      {

        recipes.map((r) => (
          <Link href={`/recipes/${r.slug.current}`} passHref  key={r._id}>
            <div>
              <h2>{r.name}</h2>
              {/* <Image src={urlFor(r.mainImage).url()} alt="done"            / > */}
              <img src={urlFor(r.mainImage).url()} height="300px" width="300px" alt="ds" />
              {/* <img src={r.mainImage.asset._ref} height="300px" width="300px" alt="" /> */}
            </div>
          </Link>

        ))}


    </div>
  )
}

export async function getStaticProps() {
  const recipes = await sanityClient.fetch(recipiesQuery);
  return { props: { recipes } };
}